In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [2]:
df = pd.read_csv("Multiclass classification Mobile price.csv")

print("Dataset preview:")
print(df.head())

Dataset preview:
   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_scr

In [3]:
target = "price_range"

X = df.drop(target, axis=1)
y = df[target]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [9]:
rf_classifier = RandomForestClassifier(
    n_estimators=10,                        
    criterion='gini',
    max_samples=int(X_train.shape[0] * 0.8), 
    min_impurity_decrease=0.1,
    max_depth=3,
    max_features=None,                      
    oob_score=True,                     
    random_state=42
)


rf_classifier.fit(X_train, y_train)

/Users/sandrinezenati/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


RandomForestClassifier(max_depth=3, max_features=None, max_samples=1280,
                       min_impurity_decrease=0.1, n_estimators=10,
                       oob_score=True, random_state=42)

In [10]:
y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.2f}")

oob_score = rf_classifier.oob_score_
print(f"Out-of-Bag Score: {oob_score:.2f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 0.74
Out-of-Bag Score: 0.72

Confusion Matrix:
[[75 25  0  0]
 [ 7 80 13  0]
 [ 0 27 57 16]
 [ 0  0 16 84]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.75      0.82       100
           1       0.61      0.80      0.69       100
           2       0.66      0.57      0.61       100
           3       0.84      0.84      0.84       100

    accuracy                           0.74       400
   macro avg       0.76      0.74      0.74       400
weighted avg       0.76      0.74      0.74       400

